apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
  - name: webhook.sidecars.svc
    clientConfig:
      service:
        name: webhook
        namespace: sidecars
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1USXdPREExTkRreE9Gb1hEVEk1TVRJd05UQTFORGt4T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXFWCjFLdXBWdmNLdzVhWUd6bTk3U3RZdWtwMDhYb2sxTVliazluNVptQ05JZUtKZnFHRURmTWNWakpPOEg4YTdHK2sKNHJ6Y0dBT3BqTG96ODBnYWdYRGpBUGtvNm9pMXlLdFdMVzlvc2ZhWmhuVVVQT1hybDk0QjBWOG01ZnUxVDhnLwpoejEvcndxMkRFOGFSQU42dllYZG10c0xuTW9VZFJTdTdma0wwcGxMSWlJd1B6Q3dNMU5pejNWL0Ixam42Z056CkVtZGJ3MjlDOWl4MFNvb0xaa3BiazZQdkk1ZUxydjdUbXZGTWF1Q25TcFF3TjhWVzBzNUJIVGRpMVdhR1NTWFoKcGVIVEpVMGpjblY1ZFkySGN4MTJCVEdYL0o4bnd0OFVlZitVTFNmS3grRFFMVnFRbE5kT1RwOFYrcWloMGJiUQo4aDJsQzQyY1MvRGVrUTNYRXJFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJaS9CN0JJa2xZa1E2ZHVFNy90MktzenRaQ08KckcrWlFTcW0vbDdkTVljMlFOZmdjNnpldElUVWZ4YkRKbW9ud1QxTDBRVGI0bmNVMVFNUVNmRXpIK1RwU2szMgpkMXJsNG5KYVVhYkErUXpYdDUrcmlXMFFxdlNZTitMMjRJVHo1UVlOS1I2V1RxMWJ0b1VWUnJwVEdNSjFMSHhSCndHcXBOUDIxNC9nS3UzazdiWXdxdmlvZzRRRGRIa1dDbGJOcFFzbWcyVTVOckpGY0tjUXN3bFBDSGRnamFaNUcKSndmQ2t4OHJzcVRZaXIvcUFsT2g4RHBBRFRlR2FIOGlKOWhUVFlDWFQzRDVFT0NEcncweVQ0K2ZmdmhmWnVsTwpCOThzbFNIaFN5M1FGY2FQUmtLbmdxdmlKUk94a1krcjFKYnhqT3MwU1ZVTE4zd3lSc3BmdWVLMit4QT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        sidecar-injector: enabled