apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook
  labels:
    app: webhook
webhooks:
  - name: webhook.sidecars.svc.cluster.local
    clientConfig:
      service:
        name: webhook
        namespace: sidecars
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1USXdPVEV4TlRJeE5sb1hEVEk1TVRJd05qRXhOVEl4Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUJDCngyeGluUnVyU0ZnZjF1clRPT3ZyUmlFckYzNTFWMEc4djl5cGZsR1RLZkpHbXh0N0RJakd3SzdSY00yNzhKWHkKanV4ME9OYUNNd1VnVEg4NGJ4T2d3WFdaNnF6K2FPZ3pLK1ljMzdPOWxoMlNKcktoa0FYL2szamZtTHFubi82bgpTWW10dGdXTVVoMVJtWjd3UTRIeFRwNUlHNkpwVDVPblJaNkx6cVp0VkhmWVJBNEZ2WDN0blJvdFpudHplRHJrCmYxbzFWeGp6Y0t4VmJSZXlzWkJrM0RKZ3J5VmprMllDL21saWFFM0psVjgyS0g1Ym5DTzl2V2F1UDBnMnBaZlMKbFM5eW5pMjJTaGoraGp6Tm1rMk96WUdmZHUrODAvdm5rZHJ6Q1pkcTAreXNkVEVPemcrTGNSbTB0TUFBNzNKOApWSERpeWxVTTVhNkt0SDVlYmVrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFNQXZsNFhOdkFhSUcxTlV0ak8yMDhIaU1tUncKeDlYWkRoQ0xSeWJsRGIraUpyYzFOOWxTdXV0eEY2VnJSWndiK01RczNFYnY0TGtJVFRoQStHME4rdUFVMExIQwp6L1lyeWlJMnR1ZkxiczhRcTN1bzljUjRKeWt0aDhnd3ZlNzhCYmo4NDljVUtkaS9qNnd1bTB1YldTSlUzNkhCClRZQjVsZnNuRExTNytEZ0thUGExMitsd0FyQ2ZWUE9zekJuOTRvNERLYy9zYXBVOEFTYmZPQ2JBYXhDRXdBZ2cKa2JUMXBqSy9Xc2pqSHJZallOQjF0SWtSK29Uc2E0NlpGQ0UxUjk3QmlqK1lJek9yWkYvZjlGcjErSUduRzR1eQoyRWVsVzdkZS8rZjdkRkRCOEt5Tis0OU5yUWFNSGwxN2JhYTRQMGMwSy9MWFFBeUJ1ZENJdXRyNk9aND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
